### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by tormodstromme** [kaschioudi/ojs3-markup#71]
When running the plugin we get this message under Job status: An unexpected error occured. 
From our log:
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to fetch job status.' in  ..../plugins/generic/markup/classes/XMLPSWrapper.inc.php:195\nStack trace:
#0 ..../plugins/generic/markup/MarkupHandler.inc.php(484): XMLPSWrapper->getJobStatus(NULL)
#1 [internal function]: MarkupHandler->fetchConversionJobStatus(Array, Object(Request))
#2 ..../lib/pkp/classes/core/PKPRouter.inc.php(372): call_user_func(Array, Array, Object(Request)
#3 ..../boap-ojs-test/lib/pkp/classes/core/PKPPageRouter.inc.php(232): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#4 ..../boap-ojs-test/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))
#5 ..../boap-ojs-test/lib/pkp/classes/core/PKPApplication.inc.php(247): Dispatcher->dispatch(Object(Request))
#6 ..../boap-ojs-test/index.php(68): PKPApplication->execute()\n#7 {main}\n  thrown in ..../plugins/generic/markup/classes/XMLPSWrapper.inc.php on line 195, referer: https://..../workflow/index/2/1

Any idea what might be wrong?

**Comment by axfelix** [comment]
Not a clear one, unfortunately, though I've seen reports of this before. It's possible that your server isn't making CURL requests to an OTS instance properly; I assume you have php-curl installed. At the moment we're trying to deprecate this plugin and get the OTS functionality and Texture functionality pulled out separately, so I can't investigate too much, but let me know here if you find anything.
